#ifndef VERSION_H
#define VERSION_H

#ifndef QT_STRINGIFY
#define QT_STRINGIFY2(x) #x
#define QT_STRINGIFY(x) QT_STRINGIFY2(x)
#endif

//Version
#define MAJORVERSION 1
#define MINORVERSION 1
#define PATCHVERSION 0
#define PROGRAMVERSION QT_STRINGIFY(MAJORVERSION.MINORVERSION.PATCHVERSION)
#define PROGRAMVERSION_NUMBER MAJORVERSION,MINORVERSION,PATCHVERSION
#define GUID "{5A071182-4831-46C4-A922-FF1E8AFAAF1D}"

#endif // VERSION_H
